import { IonButton, IonButtons, IonContent, IonFooter, IonHeader, IonIcon, IonImg, IonInput, IonItem, IonLabel, IonList, IonModal, IonPage, IonSearchbar, IonTitle, IonToolbar } from '@ionic/react';
import './Chat.css';
import { faker } from '@faker-js/faker';
import { useState } from 'react';
import { chevronBack } from 'ionicons/icons';


const Tab2: React.FC = () => {
  const chatData_ = [];
  for (var i = 0; i < 20; i++) {
    chatData_.push({
      id: i,
      avatar: faker.image.urlLoremFlickr({ category: 'abstract' }),
      name: faker.internet.displayName(),
      preview: faker.lorem.sentence()
    })
  }

  const [chat, setChat] = useState([
    {
      "role": "system",
      "content": "You are to demo a chat feature in an app. Act like a human and do not say you are a chatbot in the content, it is for demo only. This app is for renting and listing items. Add [Generated by GPT for demo only] at the end."
    },
    // {
    //   "role": "user",
    //   "content": "Hey!"
    // },
    // {
    //   "role": "user",
    //   "content": "Hi Alice! I'm doing well, thanks. How about you?"
    // },
    // {
    //   "role": "assistant",
    //   "content": "I'm good too, thanks for asking!"
    // },
    // {
    //   "role": "user",
    //   "content": "Oh, what kind of equipment are you renting?"
    // },
    // {
    //   "role": "assistant",
    //   "content": "We're renting an HPLC-ICP-MS and an ICP-MS."
    // },
    // {
    //   "role": "user",
    //   "content": "Wow, that sounds pretty specialized. What are you planning to do with them?"
    // },
    // {
    //   "role": "assistant",
    //   "content": "We're planning to analyze some environmental samples for trace metal content. It's part of a research project I'm working on."
    // },
    // {
    //   "role": "user",
    //   "content": "That sounds fascinating! I hope you get some interesting results."
    // },
    // {
    //   "role": "assistant",
    //   "content": "Thank you! We're excited to see what we'll discover. How about you? Anything exciting happening on your end?"
    // },
    // {
    //   "role": "user",
    //   "content": "I'm planning a weekend getaway with my friends. Can't wait!"
    // }
  ])
  const [chatData, setChatData] = useState(chatData_)
  const [open, setOpen] = useState(false);
  const [currentName, setCurrentName] = useState("")
  return (
    <IonPage>
      <IonModal isOpen={open}>
        <IonHeader>
          <IonToolbar>
            <IonTitle>{currentName}</IonTitle>
            <IonButtons>
              <IonButton onClick={() => { setOpen(false) }}><IonIcon aria-hidden="true" icon={chevronBack} /></IonButton>
            </IonButtons>
          </IonToolbar>
        </IonHeader>
        <IonContent>
          {
            chat.map((x, index) => {
              if (!x.content) {
                return (<></>)
              }
              if (x.role == "user") {
                return (
                  <div className='rounded-lg bg-sky-300 float-right p-2 m-2 ml-4 mr-4 w-9/12'>
                    {x.content}
                  </div>
                )
              }
              else if (x.role != "system")
                return (
                  <div className='float-left'>
                    <img className="rounded-full aspect-square w-9 float-left m-2" src={faker.image.urlLoremFlickr({ category: 'abstract' })}></img>
                    <div className='rounded-lg bg-gray-300 p-2 m-2 ml-12 mr-4 w-9/12'>
                      {x.content}
                    </div>
                  </div>
                )
            })
          }

        </IonContent>
        <IonFooter>
          <IonToolbar>
            <IonInput id="inp" placeholder='Input message here' onIonChange={() => {
              //@ts-ignore
              chat.push({ role: "user", content: document.getElementById("inp").value })
              setChat([...chat])

              fetch("https://api.openai.com/v1/chat/completions", {
                headers: { Authorization: `Bearer ${localStorage.getItem("APIKey")}`, "Content-Type": "application/json" },
                method: "POST", body: JSON.stringify(
                  {
                    "model": "gpt-4",
                    "messages": chat
                  }
                )
              }).then(x => x.json()).then(x => {
                chat.push({ role: "assistant", content: x.choices[0].message.content })
                setChat([...chat])
              }

              )
              //@ts-ignore
              document.getElementById("inp").value = ""
            }}></IonInput>
            {/* <IonButtons slot="end"><IonButton onTouchStart={()=>{
              //@ts-ignore
              if(!document.getElementById("inp").value)
              {
                return
              }
              chat.push({username: "user", content: [document.getElementById("inp").value]})
              setChat([...chat])
              //@ts-ignore
              document.getElementById("inp").value = ""
            }}><IonIcon icon={paperPlane}></IonIcon></IonButton></IonButtons> */}
          </IonToolbar>
        </IonFooter>

      </IonModal>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Chat</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent fullscreen>
        <IonHeader collapse="condense">
          <IonToolbar>
            <IonTitle size="large">Chat</IonTitle>
          </IonToolbar>
        </IonHeader>
        <IonSearchbar onIonChange={(e) => {
          setChatData([...chatData.filter((x) => {
            console.log(e)
            return x.name.includes(e.detail.value)
          })])
        }}></IonSearchbar>
        <IonList>
          {
            chatData.map(x => (
              <IonItem onClick={() => { setOpen(true); setCurrentName(x.name) }} key={x.id}>
                <img slot="start" className='rounded-full h-14 aspect-square' src={x.avatar}></img>
                <div>
                  <IonLabel><b>{x.name}</b></IonLabel>
                  <IonLabel>{x.preview}</IonLabel>
                </div>
              </IonItem>
            ))
          }
        </IonList>
      </IonContent>
    </IonPage>
  );
};

export default Tab2;
